remove ping calnex test
Summary:
This test fails on fedora infra due to insufficient permissions
```
ok  	github.com/facebook/time/calnex/verify	0.004s
github.com/facebook/time/calnex/verify/checks
 --- FAIL: TestPing (0.00s)
    ping_test.go:34:
        	Error Trace:	/builddir/build/BUILD/time-e3e1421a09800072c696a69cc5e9b71d75225724/_build/src/github.com/facebook/time/calnex/verify/checks/ping_test.go:34
        	Error:      	Received unexpected error:
        	            	socket: permission denied
        	Test:       	TestPing
```

Reviewed By: vvfedorenko

Differential Revision: D70975202