fix golang-github-facebook-time packit script (#480)
Summary:
Pull Request resolved: https://github.com/facebook/time/pull/480

The packit rpm build script were failing causing the CI checks in github to fail.
{F1983833122}

attempt to fix the packit yaml by modifying the spec and pulling the other required source files as well

Also commenting out i386 arch due to lack of support from fedora any longer.

Meta's Time libraries

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
```

But just that is not enough.
Then we run `packit srpm` to check if it working
```
[root@devvm30275 time]# packit srpm
/usr/lib/python3.14/site-packages/pyforgejo/core/pydantic_utilities.py:19: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.datetime_parse import (  # type: ignore # pyright: ignore[reportMissingImports] # Pydantic v2
2025-11-28 17:12:40.101 cmd.py            INFO   git remote get-url --all origin -> 0; stdout: 'https://github.com/facebook/time'
...
2025-11-28 17:12:42.481 upstream.py       INFO   No tags found in the repository.
2025-11-28 17:12:42.742 api.py            INFO   Directory with sources: /home/time
2025-11-28 17:12:42.790 commands.py       ERROR  Command 'rpmbuild -bs --define _sourcedir /home/time --define _srcdir /home/time --define _specdir /home/time --define _srcrpmdir /home/time --define _topdir /home/time --define _builddir /home/time --define _rpmdir /home/time --define _buildrootdir /home/time golang-github-facebook-time.spec' failed.
2025-11-28 17:12:42.791 upstream.py       ERROR  The `rpmbuild` command failed: PackitCommandFailedError("Command 'rpmbuild -bs --define _sourcedir /home/time --define _srcdir /home/time --define _specdir /home/time --define _srcrpmdir /home/time --define _topdir /home/time --define _builddir /home/time --define _rpmdir /home/time --define _buildrootdir /home/time golang-github-facebook-time.spec' failed.")
2025-11-28 17:12:42.791 command_handler.py INFO   Nothing to clean.
2025-11-28 17:12:42.791 utils.py          ERROR  reason:
Command 'rpmbuild -bs --define _sourcedir /home/time --define _srcdir /home/time --define _specdir /home/time --define _srcrpmdir /home/time --define _topdir /home/time --define _builddir /home/time --define _rpmdir /home/time --define _buildrootdir /home/time golang-github-facebook-time.spec' failed.
command:
rpmbuild -bs --define _sourcedir /home/time --define _srcdir /home/time --define _specdir /home/time --define _srcrpmdir /home/time --define _topdir /home/time --define _builddir /home/time --define _rpmdir /home/time --define _buildrootdir /home/time golang-github-facebook-time.spec
stdout:
setting SOURCE_DATE_EPOCH=1764288000

RPM build warnings:

RPM build errors:

stderr:
warning: /home/time/golang-github-facebook-time.spec line 142: autopatch: no matching patches in range
error: Bad file: /home/time/time-e9709449e79640824d668ec278f89e490df48bf5-vendor.tar.bz2: No such file or directory
error: Bad file: /home/time/go-vendor-tools.toml: No such file or directory
    /home/time/golang-github-facebook-time.spec line 142: autopatch: no matching patches in range
    Bad file: /home/time/time-e9709449e79640824d668ec278f89e490df48bf5-vendor.tar.bz2: No such file or directory
    Bad file: /home/time/go-vendor-tools.toml: No such file or directory

```

We now run into another error regarding the absence of go-vendor-tools file and vendor tarball. We can see them as sources mentioned in the spec file as well (https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/golang-github-facebook-time.spec)
```
 # Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml
```

We can also use the spectool to list the files
> but unfortunately they were not being downloaded using spectool as it seems to require them in a url format
so we just curl them instead as we anyway have to create the url - similar path as the spec file
```
[root@devvm30275 time]# spectool -f golang-github-facebook-time.spec
warning: golang-github-facebook-time.spec line 142: autopatch: no matching patches in range
Source0: time-0^20251021gite970944.tar.gz
Source1: time-e9709449e79640824d668ec278f89e490df48bf5-vendor.tar.bz2
Source2: go-vendor-tools.toml
spectool -f --gf golang-github-facebook-time.spec
warning: golang-github-facebook-time.spec line 142: autopatch: no matching patches in range
```
We can find the .toml file at https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/go-vendor-tools.toml
and we can see that the sources on the url : https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/sources

so we change the `post-upstream-clone` actions to the curl the .spec file, go-vendor-tools.toml file and the vendor.tar.bz2 file as seen in the diff. (We also rename the vendor tarball to have the latest commit from upstream instead of the  one from dist-git)

>  clarify (We assume they will remain similar - I am not sure if we have to locally everytime)

Then run the `packit srpm` and it build the srpm
```
[root@devvm30275 time]# packit srpm
/usr/lib/python3.14/site-packages/pyforgejo/core/pydantic_utilities.py:19: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.datetime_parse import (  # type: ignore # pyright: ignore[reportMissingImports] # Pydantic v2
2025-11-28 17:23:57.799 cmd.py            INFO   git remote get-url --all origin -> 0; stdout: 'https://github.com/facebook/time'
2025-11-28 17:23:57.800 actions_handler.py INFO   Using user-defined script for ActionName.post_upstream_clone: [['bash', '-c', "curl -s https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/golang-github-facebook-time.spec | sed -e '/^Patch[0-9]/d' > golang-github-facebook-time.spec"], ['curl', '-s', '-o', 'go-vendor-tools.toml', 'https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/go-vendor-tools.toml'], ['bash', '-c', "curl -s https://src.fedoraproject.org/rpms/golang-github-facebook-time/raw/main/f/sources | sed 's/SHA512 (\(.*\)) = \(.*\)/\1 \2/' | while read file hash; do curl -L https://src.fedoraproject.org/repo/pkgs/rpms/golang-github-facebook-time/$file/sha512/$hash/$file -o $file; done"]]
2025-11-28 17:23:59.300 logging.py        INFO     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2025-11-28 17:23:59.301 logging.py        INFO                                    Dload  Upload   Total   Spent    Left  Speed
100  610k  100  610k    0     0   887k      0 --:--:-- --:--:-- --:--:--  886k
2025-11-28 17:23:59.999 logging.py        INFO     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2025-11-28 17:23:59.999 logging.py        INFO                                    Dload  Upload   Total   Spent    Left  Speed
100 1936k  100 1936k    0     0  2330k      0 --:--:-- --:--:-- --:--:-- 2329k
2025-11-28 17:24:00.915 upstream.py       INFO   No tags found in the repository.
2025-11-28 17:24:00.915 upstream.py       INFO   No git tags found, falling back to %version in the specfile.
2025-11-28 17:24:01.027 cmd.py            INFO   git cat-file --batch-check
2025-11-28 17:24:01.143 commands.py       ERROR  Command 'git describe --tags --long --match *' failed.
2025-11-28 17:24:01.144 upstream.py       INFO   Exception while describing the repository: PackitCommandFailedError("Command 'git describe --tags --long --match *' failed.")
2025-11-28 17:24:01.302 commands.py       ERROR  Command 'git describe --tags --long --match *' failed.
2025-11-28 17:24:01.302 upstream.py       INFO   Exception while describing the repository: PackitCommandFailedError("Command 'git describe --tags --long --match *' failed.")
2025-11-28 17:24:02.248 upstream.py       INFO   Version retrieved from release-monitoring.org is None.
2025-11-28 17:24:02.249 base_git.py       INFO   Version in spec file is '0^20251021gite970944'.
2025-11-28 17:24:02.249 upstream.py       INFO   Picking version '0^20251021gite970944' found in spec file.
2025-11-28 17:24:02.386 upstream.py       INFO   No tags found in the repository.
2025-11-28 17:24:02.650 api.py            INFO   Directory with sources: /home/time
2025-11-28 17:24:02.869 command_handler.py INFO   Nothing to clean.
2025-11-28 17:24:02.870 srpm.py           INFO   SRPM: /home/time/golang-github-facebook-time-0^20251021gite970944-1.20251128172401303271.main.fc43.src.rpm
```

We have been facing more issues during the copr build - even after fetching all the source files from fedora's look aside cache as shown below
```
96/98] Installing libpcap-devel-14:1.1 100% |  66.6 MiB/s | 272.7 KiB |  00m00s
[97/98] Installing annobin-plugin-gcc-0 100% |  68.5 MiB/s |   1.1 MiB |  00m00s
[98/98] Installing gcc-plugin-annobin-0 100% | 406.5 KiB/s |  70.7 KiB |  00m00s
Complete!
Finish: build setup for golang-github-facebook-time-0^20251021gite970944-1.20251204120654463234.pr480.fc41.src.rpm
Start: rpmbuild golang-github-facebook-time-0^20251021gite970944-1.20251204120654463234.pr480.fc41.src.rpm
Building target platforms: aarch64
Building for target aarch64
warning: /builddir/build/originals/golang-github-facebook-time.spec line 142: autopatch: no matching patches in range
setting SOURCE_DATE_EPOCH=1764806400
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.xtD1f0
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Rk7lXg
+ umask 022
+ cd /builddir/build/BUILD/golang-github-facebook-time-0_20251021gite970944-build
+ cd /builddir/build/BUILD/golang-github-facebook-time-0_20251021gite970944-build
+ rm -rf time-e9709449e79640824d668ec278f89e490df48bf5
+ /usr/lib/rpm/rpmuncompress -x '/builddir/build/SOURCES/time-0^20251021gite970944.tar.gz'
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd time-e9709449e79640824d668ec278f89e490df48bf5
/var/tmp/rpm-tmp.Rk7lXg: line 42: cd: time-e9709449e79640824d668ec278f89e490df48bf5: No such file or directory

RPM build warnings:

RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.Rk7lXg (%prep)
    /builddir/build/originals/golang-github-facebook-time.spec line 142: autopatch: no matching patches in range
    Bad exit status from /var/tmp/rpm-tmp.Rk7lXg (%prep)
Finish: rpmbuild golang-github-facebook-time-0^20251021gite970944-1.20251204120654463234.pr480.fc41.src.rpm
Finish: build phase for golang-github-facebook-time-0^20251021gite970944-1.20251204120654463234.pr480.fc41.src.rpm
INFO: chroot_scan: 1 files copied to /var/lib/copr-rpmbuild/results/chroot_scan
INFO: /var/lib/mock/fedora-41-aarch64-1764850052.999789/root/var/log/dnf5.log
INFO: chroot_scan: creating tarball /var/lib/copr-rpmbuild/results/chroot_scan.tar.gz
/bin/tar: Removing leading `/' from member names
ERROR: Exception(/var/lib/copr-rpmbuild/results/golang-github-facebook-time-0^20251021gite970944-1.20251204120654463234.pr480.fc41.src.rpm) Config(fedora-41-aarch64) 0 minutes 8 seconds
INFO: Results and/or logs in: /var/lib/copr-rpmbuild/results
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
INFO: unmounting tmpfs.
Finish: clean chroot
ERROR: Command failed:
 # ['bash', '--login', '-c', '/usr/bin/rpmbuild -br  --target aarch64 --nodeps /builddir/build/originals/golang-github-facebook-time.spec']

Copr build error: Build failed
```
We can see from the error the since the tar file has a version based name it is extracted into a version based folder as well but The forge macros in the spec (%{forgesetupargs}) expect the directory to be time-%{commit} (full commit hash), not time-%{version} (version string).

so we overwrite the packit archive creation step and change the name
```
create-archive:
  - "bash -c 'git archive --prefix time-$(git rev-parse HEAD)/ --output time-$(git rev-parse HEAD).tar.gz HEAD'"
  - "bash -c 'echo time-$(git rev-parse HEAD).tar.gz'"
```

Default Packit Behaviour	: Creates time-0^20251203gitSHORT.tar.gz and Extracts to time-0^20251203gitSHORT/
Our Override : Creates time-<full_commit_hash>.tar.gz and Extracts to time-<full_commit_hash>/

We still face another build issue
```
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.Uiw3rs
+ umask 022
+ cd /builddir/build/BUILD/golang-github-facebook-time-0_20251203git0648c67-build
+ cd time-0648c67b71d848f1c381f027def56a633f7ae395
+ cd cmd/fbclock-bin
+ /usr/bin/make -O -j4 V=1 VERBOSE=1
gcc -g -lrt -o fbclock-bin fbclock-bin.c ../../fbclock/fbclock.c
+ mv fbclock-bin /builddir/build/BUILD/golang-github-facebook-time-0_20251203git0648c67-build/time-0648c67b71d848f1c381f027def56a633f7ae395/_build/bin/fbclock-bin
mv: cannot move 'fbclock-bin' to '/builddir/build/BUILD/golang-github-facebook-time-0_20251203git0648c67-build/time-0648c67b71d848f1c381f027def56a633f7ae395/_build/bin/fbclock-bin': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.Uiw3rs (%build)
    /builddir/build/originals/golang-github-facebook-time.spec line 142: autopatch: no matching patches in range
    Bad exit status from /var/tmp/rpm-tmp.Uiw3rs (%build)

RPM build warnings:

RPM build errors:
Finish: rpmbuild golang-github-facebook-time-0^20251203git0648c67-1.20251203180338719932.pr480.fc41.src.rpm
```
Seems like the C binary builds before Go binaries, so %{gobuilddir}/bin/ doesn't exist yet; create it first - `s|mv fbclock-bin ...|mkdir -p ... && mv ...|	`

> But I do see that fedora dropped support for i386 so if its okay to remove ?

Reviewed By: leoleovich

Differential Revision: D88011119

fbshipit-source-id: d0ee536476a4e282a3e95946818a82cd4e5f18b7