make fbclock-bin compile in mock root
Summary:
It fails because project root in mock build is not `time`, it's `time-<commit>`:
```
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.ELzalV
+ umask 022
+ cd /builddir/build/BUILD/golang-github-facebook-time-0_20250320git7aa5a0f-build
/builddir/build/BUILD/golang-github-facebook-time-0_20250320git7aa5a0f-build/time-7aa5a0f301b66872715509922356dc6a95090ef0
gcc -Wall -g -lrt -msse4.2 -std=gnu11 -o fbclock-bin -I ../../../ fbclock-bin.c ../../fbclock/fbclock.c
fbclock-bin.c:17:10: fatal error: time/fbclock/fbclock.h: No such file or directory
   17 | #include "time/fbclock/fbclock.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
```

Differential Revision: D71617115